let db=[],cst=[],inv=[],dPg={},cApp=null,cC='games',sz=6,u={p:[],r:[],n:'Guest',t:'Player',a:'https://placehold.co/100/2563eb/fff?text=U',usn:'guest',devPg:{}};
const aiA=[...Array(40)].flatMap((_,i)=>[`https://api.dicebear.com/7.x/micah/svg?seed=M${i}&backgroundColor=2563eb,10b981`,`https://api.dicebear.com/7.x/bottts/svg?seed=B${i}&backgroundColor=ef4444,8b5cf6`,`https://api.dicebear.com/7.x/avataaars/svg?seed=A${i}&backgroundColor=f59e0b,ec4899`,`https://api.dicebear.com/7.x/lorelei/svg?seed=L${i}&backgroundColor=3b82f6,14b8a6`]);
let aiI=0,cAiS='',gO='',tTmr=null;const $=i=>document.getElementById(i);let vp=navigator.vibrate||function(){};
window.onerror=()=>!0;document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('keydown',e=>{if(e.key==='F12'||(e.ctrlKey&&e.shiftKey&&e.key==='I'))e.preventDefault()});console.clear();
const iDB=()=>new Promise((r,e)=>{let R=indexedDB.open('kbs_db',1);R.onupgradeneeded=()=>R.result.createObjectStore('s');R.onsuccess=()=>r(R.result);R.onerror=()=>e(R.error)});
const sDb=async(k,v)=>{let d=await iDB();return new Promise(r=>{let t=d.transaction('s','readwrite');t.objectStore('s').put(v,k);t.oncomplete=r})};
const gDb=async(k)=>{let d=await iDB();return new Promise(r=>{let R=d.transaction('s').objectStore('s').get(k);R.onsuccess=()=>r(R.result)})};
const getDb=()=>[...db,...cst].sort((a,b)=>new Date(b.updated)-new Date(a.updated));
const rF=f=>new Promise(r=>{let R=new FileReader();R.onload=e=>r(e.target.result);R.readAsDataURL(f)});
window.onload=async()=>{try{cst=(await gDb('cst'))||[];let acts=(await gDb('acts'))||[];let curUsn=await gDb('curU');if(curUsn){let found=acts.find(x=>x.usn===curUsn);if(found)u=found;else chkAuTh()}else chkAuTh()}catch(e){}let st=Date.now(),dt=null,er=!1;try{let r=await fetch('./data.json');if(r.ok)dt=await r.json();else er=!0}catch(e){er=!0}let el=Date.now()-st;if(el<2000)await new Promise(r=>setTimeout(r,2000-el));if(er){$('ldr-msg').style.display='inline-flex';$('sp-ldr').style.display='none'}else{if(dt){db=dt.items||[];inv=dt.invites||[];dPg=dt.devPages||{}}let fi=document.querySelector('.nitem');if(fi)sw('games',fi);let l=$('ldr');l.style.opacity='0';setTimeout(()=>l.style.display='none',400)}};
async function rU(){$('u-ic').src=u.a;$('pf-ic').src=u.a;$('u-tag').value=u.t;$('u-nm').value=u.n;let f=getDb();if(u.p.length){$('pn-g').innerHTML=u.p.map(id=>{let x=f.find(z=>String(z.id)===String(id));return x?cG(x):''}).join('');$('u-sec').style.display='block'}else{$('pn-g').innerHTML='';if(!u.r.length)$('u-sec').style.display='none'}if(u.r.length){$('rc-g').innerHTML=u.r.map(id=>{let x=f.find(z=>String(z.id)===String(id));return x?cG(x):''}).join('');$('u-sec').style.display='block'}else{$('rc-g').innerHTML='';if(!u.p.length)$('u-sec').style.display='none'}rAcL()}
function tst(m){let t=$('toast');clearTimeout(tTmr);t.classList.remove('st');void t.offsetWidth;t.innerText=m;t.classList.add('st');vp(50);tTmr=setTimeout(()=>t.classList.remove('st'),5000)}
function cG(i,rk=0){return `<div class="crd-w"><div class="crd" onclick="oDv('${i.id}')">${rk>0?`<div class="rk-bdg">${rk}</div>`:''} <img src="${i.icon||'https://placehold.co/200/2563eb/fff?text=App'}" loading="lazy" decoding="async" style="border-radius:22%;box-shadow:0 4px 12px rgba(0,0,0,.08)"><div class="c-t">${i.title||'Unknown'}</div>${!i.isCustom?`<div class="c-s">${i.size||'10MB'} • ${i.rate||'5.0'}</div>`:''}</div></div>`}
function sw(c,el){cC=c;sz=6;document.querySelectorAll('.nitem').forEach(x=>x.classList.remove('act'));if(el)el.classList.add('act');$('c-ti').innerText=`All ${c.charAt(0).toUpperCase()+c.slice(1)}`;let fD=db.filter(x=>x.cat===c);$('tp-g').innerHTML=fD.slice(0,10).map((x,i)=>cG(x,i+1)).join('');$('grd').innerHTML=getDb().filter(x=>x.cat===c).slice(0,sz).map(x=>cG(x)).join('');rU();$('mn').scrollTo(0,0)}
function oDv(id){let cD=getDb();cApp=cD.find(x=>String(x.id)===String(id));if(!cApp)return;vp(10);$('d-ic').src=cApp.icon||'https://placehold.co/200';$('d-t').innerText=cApp.title||'';$('d-d').innerText=cApp.dev||'';$('d-desc').innerText=cApp.desc||'No description available.';$('d-ex').innerHTML=`<div style="font-weight:800;margin-bottom:4px;font-size:15px">App Info</div><div><i class="fa-solid fa-calendar-check" style="width:20px;color:#80868b"></i> Updated: ${cApp.updated||'-'}</div><div><i class="fa-solid fa-box" style="width:20px;color:#80868b"></i> Package: ${cApp.pkg||'-'}</div>`;if(cApp.ban){$('d-ban-w').style.display='block';$('d-ban').src=cApp.ban}else{$('d-ban-w').style.display='none';$('d-ban').src=''}let s='';if(cApp.vid)s+=`<video src="${cApp.vid}" controls poster="${cApp.img?cApp.img[0]:''}"></video>`;if(cApp.img)s+=cApp.img.map(m=>`<img src="${m}" onclick="oMv(this.src)">`).join('');$('d-sc').innerHTML=s;if(cApp.isCustom){$('d-s').innerHTML=`Local Custom Node • v${cApp.ver||'1.0.0'}`;$('d-stats').style.display='none';$('d-m-w').style.display='none';if(cApp.dev===u.n)$('d-tags').innerHTML=`<button class="btn" style="background:#f59e0b" onclick="eCon('${cApp.id}')"><i class="fa-solid fa-pen"></i> Edit App Node</button>`}else{$('d-s').innerHTML=`${cApp.size||'10MB'} • v${cApp.ver||'1.0.0'}`;$('d-stats').style.display='flex';$('d-stats').innerHTML=`<div class="stat-i"><span class="stat-v">${cApp.rate||'5.0'} <i class="fa-solid fa-star" style="font-size:12px;color:#f59e0b"></i></span><span class="stat-l">Reviews</span></div><div class="stat-i"><span class="stat-v">${cApp.downloads||'1K+'}</span><span class="stat-l">DLs</span></div><div class="stat-i"><span class="stat-v">${cApp.age||'3+'}</span><span class="stat-l">Rated</span></div>`;$('d-tags').innerHTML=(cApp.tags||['App']).map(t=>`<span class="tg">${t}</span>`).join('');let mDev=db.filter(x=>x.dev===cApp.dev&&String(x.id)!==String(id));$('d-more-dev').innerHTML=mDev.length?mDev.slice(0,5).map(x=>cG(x)).join(''):'<div style="font-size:13px;color:#80868b">ไม่มีผลงานอื่น</div>';$('d-m-w').style.display='block'}let b=$('d-b');if(cApp.cat==='games'||cApp.cat==='apps'){b.innerHTML='<i class="fa-solid fa-play"></i> เล่น';b.onclick=()=>pKs(cApp);b.style.background='var(--p)';b.style.color='#fff'}else{b.innerHTML='<i class="fa-solid fa-download"></i> ดาวน์โหลด';b.onclick=()=>shwDl(cApp);b.style.background='#10b981';b.style.color='#fff'}$('p-btn').style.color=u.p.includes(String(id))?'var(--p)':'#80868b';$('dv').classList.add('show');history.pushState({p:'dv'},"")}
function cDv(){$('dv').classList.remove('show');cApp=null;$('d-ban').src='';$('d-sc').innerHTML=''}
async function tPin(){if(!cApp)return;let id=String(cApp.id),i=u.p.indexOf(id);if(i>-1){u.p.splice(i,1);$('p-btn').style.color='#80868b';tst('Unpinned')}else{if(u.p.length>=10){tst('Max 10 pins');return}u.p.unshift(id);$('p-btn').style.color='var(--p)';tst('Pinned')}await svU();vp(20)}
async function svU(){let acts=(await gDb('acts'))||[];let idx=acts.findIndex(x=>x.usn===u.usn);if(idx>-1)acts[idx]=u;else acts.push(u);await sDb('acts',acts);await sDb('curU',u.usn);rU()}
async function pKs(a){try{let id=String(a.id);u.r=u.r.filter(x=>x!==id);u.r.unshift(id);if(u.r.length>10)u.r.pop();await svU();let f=$('plyr');f.style.display='block';setTimeout(()=>f.classList.add('play'),50);if(f.requestFullscreen)f.requestFullscreen();f.src=a.fileSrc||a.link||'';history.pushState({p:'ply'},"")}catch(e){tst("Engine Launch Failed")}}
function xPly(){let f=$('plyr');f.classList.remove('play');setTimeout(()=>{f.style.display='none';f.src=''},400);if(document.fullscreenElement)document.exitFullscreen()}
window.onpopstate=e=>{if($('plyr').classList.contains('play'))xPly();else if($('ai-mod').classList.contains('show'))cAi();else if($('con-mod').classList.contains('show'))cCon();else if($('dev-pg').classList.contains('show'))cDevPg();else if($('mod').classList.contains('show'))cMod();else if($('f-del').classList.contains('act'))cDel();else if($('dl-mod').style.display==='flex')cDl();else if(!$('auth-mod').classList.contains('hide'))return;else cDv()};
$('sinp').addEventListener('input',e=>{let v=e.target.value.toLowerCase();if(!v)sw(cC,document.querySelector('.nitem.act'));else{$('grd').innerHTML=getDb().filter(x=>(x.title||'').toLowerCase().includes(v)||(x.dev||'').toLowerCase().includes(v)||(x.desc||'').toLowerCase().includes(v)).map(x=>cG(x)).join('')}});
function shApp(){if(navigator.share&&cApp)navigator.share({title:cApp.title,text:cApp.desc,url:window.location.href})}
function oMod(){$('mod').classList.add('show');history.pushState({p:'mod'},"")}function cMod(){$('mod').classList.remove('show')}
function trgFl(){let fl=$('flt'),im=$('fl-i');im.src=u.a;fl.classList.remove('shrink');fl.classList.add('act');setTimeout(()=>{fl.classList.add('shrink');setTimeout(()=>{fl.classList.remove('act','shrink')},600)},3000)}
async function sUsr(){u.t=$('u-tag').value;u.n=$('u-nm').value;await svU();cMod();trgFl();tst('Profile Saved successfully')}
function oAi(){$('ai-mod').classList.add('show');history.pushState({p:'ai'},"");gAi()}function cAi(){$('ai-mod').classList.remove('show')}
function gAi(){$('ai-st').innerText='Generating with Nat Pro Nano...';$('ai-grd').innerHTML='';$('ai-sv').style.display='none';cAiS='';let r=[];for(let i=0;i<3;i++){r.push(aiA[aiI]);aiI++;if(aiI>=aiA.length)aiI=0}setTimeout(()=>{$('ai-st').innerText='Select your unique avatar';$('ai-grd').innerHTML=r.map((x,i)=>`<img src="${x}" onclick="slAi(this,'${x}')" style="transition-delay:${i*0.1}s">`).join('');setTimeout(()=>document.querySelectorAll('.ai-g img').forEach(e=>e.classList.add('show')),50)},1000)}
function slAi(el,x){document.querySelectorAll('.ai-g img').forEach(e=>e.classList.remove('sel'));el.classList.add('sel');cAiS=x;$('ai-sv').style.display='inline-flex';vp(10)}
async function sAi(){if(!cAiS)return;u.a=cAiS;$('pf-ic').src=cAiS;await svU();cAi();cMod();trgFl();tst('Avatar Updated')}
$('mn').addEventListener('scroll',e=>{if($('sinp').value)return;let el=e.target;if(el.scrollHeight-el.scrollTop<=el.clientHeight+100&&sz<getDb().length){sz+=6;let f=getDb().filter(x=>x.cat===cC);$('grd').innerHTML=f.slice(0,sz).map(x=>cG(x)).join('')}});
function chkAuTh(){$('auth-mod').classList.remove('hide');$('sin-usn').value='';$('sin-pwd').value='';$('sup-eml').value='';$('sup-usn').value='';$('sup-pwd').value='';$('sup-name').value='';$('sup-tag').value='';$('sup-otp').value='';swAuTh('sin')}
function swAuTh(t){if(t==='sin'){$('tab-sin').classList.add('active');$('tab-sup').classList.remove('active');$('f-sin').classList.add('active');$('f-sup').classList.remove('active');$('f-otp').classList.remove('active')}else{$('tab-sup').classList.add('active');$('tab-sin').classList.remove('active');$('f-sup').classList.add('active');$('f-sin').classList.remove('active');$('f-otp').classList.remove('active')}}
async function hSin(){let usn=$('sin-usn').value.trim(),pwd=$('sin-pwd').value;if(!usn||!pwd){tst('Please fill all fields');return}let acts=(await gDb('acts'))||[];let hash=CryptoJS.SHA256(pwd+usn+"KBIOS_SEC").toString();let found=acts.find(x=>x.usn===usn&&x.pwd===hash);if(found){u=found;if(!u.devPg)u.devPg={};await sDb('curU',usn);$('auth-mod').classList.add('hide');rU();tst(`Welcome back, ${u.n}`)}else{$('s-err').classList.add('act')}}
function cErr(){$('s-err').classList.remove('act')}
async function hSup(){let eml=$('sup-eml').value.trim(),name=$('sup-name').value.trim(),tag=$('sup-tag').value.trim(),usn=$('sup-usn').value.trim(),pwd=$('sup-pwd').value;if(!eml||!name||!tag||!usn||!pwd){tst('Please fill all fields');return}if(!/^@[A-Za-z0-9]{8}\.kbiosstore$/.test(eml)){tst('Invalid Invite Format');return}if(!inv.includes(eml)){tst('Invite Key not authorized');return}let acts=(await gDb('acts'))||[];if(acts.some(x=>x.usn===usn)){tst('Username exists');return}$('auth-ldr').style.display='flex';setTimeout(()=>{$('auth-ldr').style.display='none';$('f-sup').classList.remove('active');$('f-otp').classList.add('active');rSnd()},3000)}
function rSnd(){gO=Math.floor(10000000+Math.random()*90000000).toString();let m=$('sms-msg'),b=$('sms-bar');m.innerText='PIN: '+gO;b.classList.add('show');tst('New PIN generated & sent');setTimeout(()=>b.classList.remove('show'),6000)}
async function vOtp(){let v=$('sup-otp').value.trim();if(v!==gO){tst('Invalid PIN');return}let name=$('sup-name').value.trim(),tag=$('sup-tag').value.trim(),usn=$('sup-usn').value.trim(),pwd=$('sup-pwd').value;let acts=(await gDb('acts'))||[];let hash=CryptoJS.SHA256(pwd+usn+"KBIOS_SEC").toString();let ic=`https://placehold.co/100/2563eb/fff?text=${name.charAt(0).toUpperCase()}`;let nU={p:[],r:[],n:name,t:tag,a:ic,usn:usn,pwd:hash,devPg:{}};acts.push(nU);await sDb('acts',acts);u=nU;await sDb('curU',usn);$('auth-mod').classList.add('hide');rU();trgFl();tst('Account Created Successfully')}
async function loUt(){await sDb('curU',null);cMod();cDv();chkAuTh();tst('Logged Out Securely')}
function oAuthFromProfile(){cMod();chkAuTh()}
async function rmAc(n){if(n===u.usn)oDel();else{let a=(await gDb('acts'))||[];a=a.filter(x=>x.usn!==n);await sDb('acts',a);rAcL();tst('Account removed locally')}}
async function rAcL(){let acts=(await gDb('acts'))||[];let h='';acts.forEach(x=>{let c=(x.usn===u.usn)?'<span class="ac-badge">Active</span>':'';let d=`<i class="fa-solid fa-trash ac-del" onclick="event.stopPropagation();rmAc('${x.usn}')"></i>`;h+=`<div class="ac-item" onclick="swAc('${x.usn}')"><img src="${x.a}"><div class="ac-info"><div class="ac-name">${x.n}</div><div class="ac-tag">@${x.t}</div></div>${c}${d}</div>`});$('pf-ac-list').innerHTML=h}
function swAc(usn){if(usn===u.usn)return;cMod();chkAuTh();swAuTh('sin');$('sin-usn').value=usn;tst('Authentication Required')}
function oMv(src){if(!src)return;vp(15);$('mv-img').src=src;$('media-viewer').classList.add('show')}
function cMv(){$('media-viewer').classList.remove('show');setTimeout(()=>{$('mv-img').src=''},300)}
let dS=1;function oDel(){$('f-del').classList.add('act');dS=1;uDel()}function cDel(){$('f-del').classList.remove('act')}
function uDel(){for(let i=1;i<=4;i++){$('ds'+i).classList[dS===i?'add':'remove']('act')}}
async function nDel(s){if(s===2)dS=2;if(s===3){let p=$('d-pwd').value;let h=CryptoJS.SHA256(p+u.usn+"KBIOS_SEC").toString();if(h!==u.pwd){tst('Invalid Password');return}dS=3}if(s===5){dS=4;uDel();setTimeout(async()=>{let a=(await gDb('acts'))||[];a=a.filter(x=>x.usn!==u.usn);await sDb('acts',a);await sDb('curU',null);cDel();cMod();cDv();chkAuTh();tst('Account Eradicated')},3000);return}uDel()}
function oCon(){$('con-mod').classList.add('show');$('cn-id').value='';$('cn-ban').value='';$('cn-ic').value='';$('cn-img').value='';$('cn-vid').value='';$('cn-t').value='';$('cn-d').value='';$('cn-l').value='';$('cn-file').value='';if(u.devPg){$('cp-ban').value='';$('cp-bio').value=u.devPg.desc||'';$('cp-pin').value=u.devPg.pinned||'';if(u.devPg.links&&u.devPg.links[0]){$('cp-l1-n').value=u.devPg.links[0].name||'';$('cp-l1-u').value=u.devPg.links[0].url||'';$('cp-l1-i').value=u.devPg.links[0].icon||''}}swCon('app');history.pushState({p:'con'},"")}function cCon(){$('con-mod').classList.remove('show')}
function swCon(t){if(t==='app'){$('tab-c-app').classList.add('active');$('tab-c-pg').classList.remove('active');$('con-app-s').classList.add('active');$('con-pg-s').classList.remove('active')}else{$('tab-c-pg').classList.add('active');$('tab-c-app').classList.remove('active');$('con-pg-s').classList.add('active');$('con-app-s').classList.remove('active')}}
function eCon(id){let a=cst.find(x=>x.id===id);if(!a)return;$('cn-id').value=id;$('cn-c').value=a.cat;$('cn-t').value=a.title;$('cn-d').value=a.desc;$('cn-l').value=a.link;$('con-mod').classList.add('show');swCon('app')}
async function svPg(){let bF=$('cp-ban').files[0];let ban=bF?await rF(bF):(u.devPg.banner||'');u.devPg={banner:ban,desc:$('cp-bio').value,pinned:$('cp-pin').value,links:[]};if($('cp-l1-n').value&&$('cp-l1-u').value){u.devPg.links.push({name:$('cp-l1-n').value,url:$('cp-l1-u').value,icon:$('cp-l1-i').value||'fa-link'})}await svU();tst('Dev Page settings updated')}
async function svCon(){let id=$('cn-id').value,t=$('cn-t').value.trim(),c=$('cn-c').value,d=$('cn-d').value.trim(),l=$('cn-l').value.trim(),fS=$('cn-file').files[0];if(!t||(!l&&!fS)){tst('Title and URL/File required');return}let bF=$('cn-ban').files[0],iF=$('cn-ic').files[0],mF=$('cn-img').files,vF=$('cn-vid').files[0];let ban=bF?await rF(bF):'',ic=iF?await rF(iF):'',vid=vF?await rF(vF):'',fD=fS?await rF(fS):'',imgs=[];for(let i=0;i<Math.min(mF.length,8);i++)imgs.push(await rF(mF[i]));let nA={id:id||'cst_'+Date.now(),cat:c,title:t,dev:u.n,icon:ic||'https://placehold.co/200/10b981/fff?text=DEV',desc:d||'Local App',updated:new Date().toISOString().split('T')[0],pkg:'com.custom.'+Date.now(),ver:'1.0.0',type:fS?'file':'html',link:l,fileSrc:fD,isCustom:!0,ban:ban||'',vid:vid||'',img:imgs};if(id){let idx=cst.findIndex(x=>x.id===id);if(idx>-1)cst[idx]={...cst[idx],...nA,ban:ban||cst[idx].ban,icon:ic||cst[idx].icon,vid:vid||cst[idx].vid,fileSrc:fD||cst[idx].fileSrc,img:imgs.length?imgs:cst[idx].img}}else{cst.push(nA)}await sDb('cst',cst);cCon();if($('dv').classList.contains('show'))cDv();tst('App Published Locally!');sw(cC,document.querySelector('.nitem.act'))}
function oDevPgFromApp(){if(!cApp)return;oDevPg(cApp.dev)}
async function oDevPg(n){let pg=dPg[n];let isLcl=!1;if(!pg){let acts=(await gDb('acts'))||[];let fUsr=acts.find(x=>x.n===n);if(fUsr&&fUsr.devPg){pg=fUsr.devPg;isLcl=!0}else pg={}}let bSrc=pg.banner||`https://placehold.co/800x400/0f172a/fff?text=${n}`;let iSrc=isLcl?(acts?.find(x=>x.n===n)?.a):pg.icon||`https://placehold.co/200/1e293b/fff?text=${n.charAt(0)}`;$('dp-nm').innerText=n;$('dp-ic').src=iSrc;$('dp-ban').src=bSrc;$('dp-desc').innerText=pg.desc||'No description provided by developer.';$('dp-lnks').innerHTML=(pg.links||[]).map(l=>`<a href="${l.url}" target="_blank" class="d-ln"><i class="${l.icon||'fa-solid fa-link'}"></i> ${l.name}</a>`).join('');let f=getDb().filter(x=>x.dev===n);if(pg.pinned){let pIdx=f.findIndex(x=>String(x.id)===String(pg.pinned));if(pIdx>-1){let pItm=f.splice(pIdx,1)[0];f.unshift(pItm)}}$('dp-grd').innerHTML=f.length?f.map((x,i)=>cG(x,pg.pinned&&i===0?'Pin':0)).join(''):'<div style="color:#80868b">No apps published yet.</div>';$('dev-pg').classList.add('show');history.pushState({p:'devpg'},"")}function cDevPg(){$('dev-pg').classList.remove('show')}
let dlT=null;function shwDl(a){$('dl-ic').src=a.icon||'';$('dl-ti').innerText=a.title;$('dl-sz').innerText=a.size||'10MB';$('dl-p-w').style.display='none';$('dl-act-btn').style.display='flex';$('dl-bar').style.width='0%';$('dl-mod').style.display='flex';setTimeout(()=>{$('dl-mod').style.opacity='1';$('dl-bx').style.transform='translateY(0)'},50);history.pushState({p:'dl'},"")}
function cDl(){clearInterval(dlT);$('dl-mod').style.opacity='0';$('dl-bx').style.transform='translateY(100%)';setTimeout(()=>$('dl-mod').style.display='none',300)}
function stDl(){$('dl-act-btn').style.display='none';$('dl-p-w').style.display='block';let p=0;dlT=setInterval(()=>{p+=Math.floor(Math.random()*15)+5;if(p>=100){p=100;clearInterval(dlT);setTimeout(()=>{cDl();let b=$('d-b');b.innerHTML='<i class="fa-solid fa-folder-open"></i> เปิดไฟล์';b.onclick=()=>{if(cApp.fileSrc){pKs(cApp)}else{alert('กำลังเรียกใช้ตัวจัดการไฟล์ของระบบ...')}};b.style.background='var(--t)';tst('ดาวน์โหลดและติดตั้งเสร็จสมบูรณ์')},500)}$('dl-bar').style.width=p+'%';$('dl-pct').innerText=p+'%'},400)}