let db=[],cApp=null,cC='games',sz=6,u={p:[],r:[],n:'Guest',t:'Node',a:'https://placehold.co/100/2563eb/fff?text=U',usn:'guest_user'};
const aiA=[...Array(40)].flatMap((_,i)=>[`https://api.dicebear.com/7.x/micah/svg?seed=M${i}&backgroundColor=2563eb,10b981`,`https://api.dicebear.com/7.x/bottts/svg?seed=B${i}&backgroundColor=ef4444,8b5cf6`,`https://api.dicebear.com/7.x/avataaars/svg?seed=A${i}&backgroundColor=f59e0b,ec4899`,`https://api.dicebear.com/7.x/lorelei/svg?seed=L${i}&backgroundColor=3b82f6,14b8a6`]);
let aiI=0,cAiS='',gO='',smsT=null,dlT=null,tQ=[],tO=null,dBnc=null;
const $=i=>document.getElementById(i);
const vp=p=>{if(navigator.vibrate)navigator.vibrate(p)};
window.onerror=()=>!0;document.addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('keydown',e=>{if(e.key==='F12'||(e.ctrlKey&&e.shiftKey&&e.key==='I'))e.preventDefault()});
console.clear();console.log('%cKBIOS STORE V2 SECURE','color:#2563eb;font-size:24px;font-weight:900');
const getDb=()=>db.sort((a,b)=>new Date(b.updated)-new Date(a.updated));
window.addEventListener('online',()=>tst('Network Restored'));
window.addEventListener('offline',()=>tst('Critical: Connection Lost',1));
window.onload=async()=>{try{let lAc=localStorage.getItem('kbs_accounts');if(!lAc)localStorage.setItem('kbs_accounts',JSON.stringify([]));let curUsn=localStorage.getItem('kbs_cur_user');if(curUsn){let acts=JSON.parse(localStorage.getItem('kbs_accounts')||'[]');let found=acts.find(x=>x.usn===curUsn);if(found)u=found;else chkAuTh()}else chkAuTh()}catch(e){}let st=Date.now(),dt=null,er=!1;try{let r=await fetch('./data.json');if(r.ok)dt=await r.json();else er=!0}catch(e){er=!0}let el=Date.now()-st;if(el<2500)await new Promise(r=>setTimeout(r,2500-el));if(er||!navigator.onLine){$('ldr-msg').style.display='inline-flex';$('sp-ldr').style.display='none'}else{if(dt)db=Array.isArray(dt)?dt:dt.items||[];let fi=document.querySelector('.nitem');if(fi)sw('games',fi);let l=$('ldr');l.style.opacity='0';setTimeout(()=>l.style.display='none',500)}};
function rU(){$('u-ic').src=u.a;$('pf-ic').src=u.a;$('u-tag').value=u.t;$('u-nm').value=u.n;let f=getDb();if(u.p.length){$('pn-g').innerHTML=u.p.map(id=>{let x=f.find(z=>String(z.id)===String(id));return x?cG(x):''}).join('');$('u-sec').style.display='block'}else{$('pn-g').innerHTML='';if(!u.r.length)$('u-sec').style.display='none'}if(u.r.length){$('rc-g').innerHTML=u.r.map(id=>{let x=f.find(z=>String(z.id)===String(id));return x?cG(x):''}).join('');$('u-sec').style.display='block'}else{$('rc-g').innerHTML='';if(!u.p.length)$('u-sec').style.display='none'}rAcL()}
function tst(m,e=0){tQ.push({m,e});pTst()}
function pTst(){if(tO||!tQ.length)return;let t=tQ.shift(),el=$('toast');el.innerHTML=t.e?`<i class="fa-solid fa-triangle-exclamation" style="color:#ef4444;margin-right:8px"></i> ${t.m}`:`<i class="fa-solid fa-circle-check" style="color:#10b981;margin-right:8px"></i> ${t.m}`;el.classList.add('st');vp(t.e?[50,50,50]:50);tO=setTimeout(()=>{el.classList.remove('st');tO=null;setTimeout(pTst,300)},2500)}
function dStars(r){let v=parseFloat(r),h='';for(let i=1;i<=5;i++){if(v>=i)h+='<i class="fa-solid fa-star" style="color:#f59e0b"></i> ';else if(v>=i-0.5)h+='<i class="fa-solid fa-star-half-stroke" style="color:#f59e0b"></i> ';else h+='<i class="fa-regular fa-star" style="color:#cbd5e1"></i> '}return h}
function cG(i,rk=0){return `<div class="crd-w"><div class="crd" onclick="oDv('${i.id}')">${rk>0?`<div class="rk-bdg">${rk}</div>`:''} <div style="position:relative"><img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1 1'%3E%3C/svg%3E" data-src="${i.icon||'https://placehold.co/200/2563eb/fff'}" loading="lazy" decoding="async" onload="this.src=this.dataset.src;this.removeAttribute('data-src')" style="transition:opacity .3s;opacity:0" onloadeddata="this.style.opacity=1"></div><div class="c-t">${i.title||'Unknown'}</div><div class="c-s"><i class="fa-solid fa-star" style="color:#f59e0b;font-size:10px"></i> ${i.rate||'5.0'} • ${i.size||'10MB'}</div></div></div>`}
function sw(c,el){cC=c;sz=6;document.querySelectorAll('.nitem').forEach(x=>x.classList.remove('act'));if(el)el.classList.add('act');$('c-ti').innerText=`All ${c.charAt(0).toUpperCase()+c.slice(1)}`;let f=getDb().filter(x=>x.cat===c);$('tp-g').innerHTML=f.slice(0,10).map((x,i)=>cG(x,i+1)).join('');$('grd').innerHTML=f.slice(0,sz).map(x=>cG(x)).join('');rU();$('mn').scrollTo({top:0,behavior:'smooth'})}
function oDv(id){let cD=getDb();cApp=cD.find(x=>String(x.id)===String(id));if(!cApp)return;vp(15);$('d-ic').src=cApp.icon||'https://placehold.co/200';$('d-t').innerText=cApp.title||'';$('d-d').innerHTML=`<i class="fa-solid fa-building-shield"></i> ${cApp.dev||''}`;$('d-s').innerHTML=`${cApp.size||'10MB'} • v${cApp.ver||'1.0.0'}`;$('d-stats').innerHTML=`<div class="stat-i"><span class="stat-v">${cApp.rate||'5.0'}</span><span class="stat-l">${dStars(cApp.rate||5)}</span></div><div class="stat-i"><span class="stat-v">${cApp.downloads||'1K+'}</span><span class="stat-l">Installs</span></div><div class="stat-i"><span class="stat-v">${cApp.age||'3+'}</span><span class="stat-l">Rating</span></div>`;$('d-tags').innerHTML=(cApp.tags||['App']).map(t=>`<span class="tg">${t}</span>`).join('');$('d-desc').innerText=cApp.desc||'No description available.';$('d-ex').innerHTML=`<div style="font-weight:900;margin-bottom:8px;font-size:15px;color:var(--p)"><i class="fa-solid fa-microchip"></i> System Allocation</div><div><i class="fa-solid fa-calendar-check" style="width:20px;color:#64748b"></i> Protocol Updated: ${cApp.updated||'-'}</div><div><i class="fa-solid fa-box" style="width:20px;color:#64748b"></i> Package UID: ${cApp.pkg||'-'}</div>`;$('d-sc').innerHTML=(cApp.img||[]).map(m=>`<img src="${m}" onclick="oMv(this.src)">`).join('');let b=$('d-b');if(cApp.cat==='games'||cApp.cat==='apps'){b.innerHTML='<i class="fa-solid fa-play"></i> Execute';b.onclick=()=>pKs(cApp);b.style.background='var(--p)';b.style.color='#fff'}else{b.innerHTML='<i class="fa-solid fa-download"></i> Fetch Data';b.onclick=()=>shwDl(cApp);b.style.background='#10b981';b.style.color='#fff'}$('p-btn').style.color=u.p.includes(String(id))?'var(--p)':'#94a3b8';let mDev=cD.filter(x=>x.dev===cApp.dev&&String(x.id)!==String(id));$('d-more-dev').innerHTML=mDev.length?mDev.slice(0,5).map(x=>cG(x)).join(''):'<div style="font-size:14px;color:#64748b;font-weight:600">Unique architecture. No other packets found.</div>';$('dv').classList.add('show');history.pushState({p:'dv'},"")}
function cDv(){$('dv').classList.remove('show');cApp=null}
function tPin(){if(!cApp)return;let id=String(cApp.id),i=u.p.indexOf(id);if(i>-1){u.p.splice(i,1);$('p-btn').style.color='#94a3b8';tst('Protocol Unpinned')}else{if(u.p.length>=10){tst('Maximum 10 pins allowed',1);return}u.p.unshift(id);$('p-btn').style.color='var(--p)';tst('Protocol Pinned to Local')}svU();vp([20,30])}
function svU(){let acts=JSON.parse(localStorage.getItem('kbs_accounts')||'[]');let idx=acts.findIndex(x=>x.usn===u.usn);if(idx>-1)acts[idx]=u;else acts.push(u);localStorage.setItem('kbs_accounts',JSON.stringify(acts));localStorage.setItem('kbs_cur_user',u.usn);rU()}
function pKs(a){try{let id=String(a.id);u.r=u.r.filter(x=>x!==id);u.r.unshift(id);if(u.r.length>10)u.r.pop();svU();let f=$('plyr');f.style.display='block';setTimeout(()=>f.classList.add('play'),50);if(f.requestFullscreen)f.requestFullscreen();f.src=a.link||'';history.pushState({p:'ply'},"")}catch(e){tst("Engine Launch Failed",1)}}
function xPly(){let f=$('plyr');f.classList.remove('play');setTimeout(()=>{f.style.display='none';f.src=''},400);if(document.fullscreenElement)document.exitFullscreen()}
window.onpopstate=e=>{if($('plyr').classList.contains('play'))xPly();else if($('ai-mod').classList.contains('show'))cAi();else if($('dev-pg').classList.contains('show'))cDevPg();else if($('mod').classList.contains('show'))cMod();else if($('f-del').classList.contains('act'))cDel();else if($('dl-mod').style.display==='flex')cDl();else if(!$('auth-mod').classList.contains('hide'))return;else cDv()};
$('sinp').addEventListener('input',e=>{clearTimeout(dBnc);dBnc=setTimeout(()=>{let v=e.target.value.toLowerCase();if(!v)sw(cC,document.querySelector('.nitem.act'));else{$('grd').innerHTML=getDb().filter(x=>(x.title||'').toLowerCase().includes(v)||(x.dev||'').toLowerCase().includes(v)||(x.desc||'').toLowerCase().includes(v)||(x.tags||[]).join(' ').toLowerCase().includes(v)).map(x=>cG(x)).join('')}},300)});
function shApp(){if(navigator.share&&cApp)navigator.share({title:cApp.title,text:cApp.desc,url:window.location.href})}
function oMod(){$('mod').classList.add('show');history.pushState({p:'mod'},"")}
function cMod(){$('mod').classList.remove('show')}
function trgFl(){let fl=$('flt'),im=$('fl-i');im.src=u.a;fl.classList.remove('shrink');fl.classList.add('act');setTimeout(()=>{fl.classList.add('shrink');setTimeout(()=>{fl.classList.remove('act','shrink')},600)},3000)}
function sUsr(){u.t=$('u-tag').value;u.n=$('u-nm').value;svU();cMod();trgFl();tst('Node Configuration Saved')}
function oAi(){$('ai-mod').classList.add('show');history.pushState({p:'ai'},"");gAi()}
function cAi(){$('ai-mod').classList.remove('show')}
function gAi(){$('ai-st').innerText='Rendering Neural Architecture...';$('ai-grd').innerHTML='';$('ai-sv').style.display='none';cAiS='';let r=[];for(let i=0;i<3;i++){r.push(aiA[aiI]);aiI++;if(aiI>=aiA.length)aiI=0}setTimeout(()=>{$('ai-st').innerText='Select Output Matrix';$('ai-grd').innerHTML=r.map((x,i)=>`<img src="${x}" onclick="slAi(this,'${x}')" style="transition-delay:${i*0.1}s">`).join('');setTimeout(()=>document.querySelectorAll('.ai-g img').forEach(e=>e.classList.add('show')),50)},800)}
function slAi(el,x){document.querySelectorAll('.ai-g img').forEach(e=>e.classList.remove('sel'));el.classList.add('sel');cAiS=x;$('ai-sv').style.display='inline-flex';vp(15)}
function sAi(){if(!cAiS)return;u.a=cAiS;$('pf-ic').src=cAiS;svU();cAi();cMod();trgFl();tst('Avatar Core Updated')}
$('mn').addEventListener('scroll',e=>{if($('sinp').value)return;let el=e.target;if(el.scrollHeight-el.scrollTop<=el.clientHeight+150&&sz<getDb().length){sz+=6;let f=getDb().filter(x=>x.cat===cC);$('grd').innerHTML=f.slice(0,sz).map(x=>cG(x)).join('')}});
$('dp-scrl').addEventListener('scroll',e=>{let op=Math.min(e.target.scrollTop/150,1);$('dp-hdr-nm').style.opacity=op});
function chkAuTh(){$('auth-mod').classList.remove('hide');$('sin-usn').value='';$('sin-pwd').value='';$('sup-eml').value='';$('sup-usn').value='';$('sup-pwd').value='';$('sup-name').value='';$('sup-tag').value='';$('sup-otp').value='';swAuTh('sin')}
function swAuTh(t){if(t==='sin'){$('tab-sin').classList.add('active');$('tab-sup').classList.remove('active');$('f-sin').classList.add('active');$('f-sup').classList.remove('active');$('f-otp').classList.remove('active')}else{$('tab-sup').classList.add('active');$('tab-sin').classList.remove('active');$('f-sup').classList.add('active');$('f-sin').classList.remove('active');$('f-otp').classList.remove('active')}}
function hSin(){let usn=$('sin-usn').value.trim(),pwd=$('sin-pwd').value;if(!usn||!pwd){tst('Incomplete parameters',1);return}let acts=JSON.parse(localStorage.getItem('kbs_accounts')||'[]');let hash=CryptoJS.SHA256(pwd+usn+"KBIOS_SEC").toString();let found=acts.find(x=>x.usn===usn&&x.pwd===hash);if(found){u=found;localStorage.setItem('kbs_cur_user',usn);$('auth-mod').classList.add('hide');rU();tst(`Session restored: ${u.n}`)}else{$('s-err').classList.add('act');vp([50,50,50])}}
function cErr(){$('s-err').classList.remove('act')}
function hSup(){let eml=$('sup-eml').value.trim(),name=$('sup-name').value.trim(),tag=$('sup-tag').value.trim(),usn=$('sup-usn').value.trim(),pwd=$('sup-pwd').value;if(!eml||!name||!tag||!usn||!pwd){tst('Incomplete parameters',1);return}if(!eml.endsWith('@kbioswebaccount')){tst('Invalid Directive Key',1);return}let acts=JSON.parse(localStorage.getItem('kbs_accounts')||'[]');if(acts.some(x=>x.usn===usn)){tst('Identity Conflict: Username taken',1);return}$('f-sup').classList.remove('active');$('f-otp').classList.add('active');gO=gO||Math.floor(10000000+Math.random()*90000000).toString();setTimeout(shSms,1500)}
function rsOtp(){if(!$('f-otp').classList.contains('active'))return;shSms();tst('Retransmitting Signal')}
function shSms(){clearTimeout(smsT);let m=$('sms-msg'),b=$('sms-bar');m.innerText='AUTH PIN: '+gO;b.classList.add('show');vp([30,50,30]);smsT=setTimeout(()=>b.classList.remove('show'),5000)}
function vOtp(){let v=$('sup-otp').value.trim();if(v!==gO){tst('Hash Mismatch',1);vp([50,50]);return}let name=$('sup-name').value.trim(),tag=$('sup-tag').value.trim(),usn=$('sup-usn').value.trim(),pwd=$('sup-pwd').value;let acts=JSON.parse(localStorage.getItem('kbs_accounts')||'[]');let hash=CryptoJS.SHA256(pwd+usn+"KBIOS_SEC").toString();let ic=`https://placehold.co/200/2563eb/fff?text=${name.charAt(0).toUpperCase()}`;let nU={p:[],r:[],n:name,t:tag,a:ic,usn:usn,pwd:hash};acts.push(nU);localStorage.setItem('kbs_accounts',JSON.stringify(acts));u=nU;localStorage.setItem('kbs_cur_user',usn);$('auth-mod').classList.add('hide');gO='';rU();trgFl();tst('Identity Bound to Local Node')}
function loUt(){localStorage.removeItem('kbs_cur_user');cMod();cDv();chkAuTh();tst('Session Terminated')}
function oAuthFromProfile(){cMod();chkAuTh()}
function rmAc(n){if(n===u.usn)oDel();else{let a=JSON.parse(localStorage.getItem('kbs_accounts')||'[]');a=a.filter(x=>x.usn!==n);localStorage.setItem('kbs_accounts',JSON.stringify(a));rAcL();tst('Ghost Node Erased')}}
function rAcL(){let acts=JSON.parse(localStorage.getItem('kbs_accounts')||'[]');let h='';acts.forEach(x=>{let c=(x.usn===u.usn)?'<span class="ac-badge">Active</span>':'';let d=`<i class="fa-solid fa-trash ac-del" onclick="event.stopPropagation();rmAc('${x.usn}')"></i>`;h+=`<div class="ac-item" onclick="swAc('${x.usn}')"><img src="${x.a}"><div class="ac-info"><div class="ac-name">${x.n}</div><div class="ac-tag">@${x.t}</div></div>${c}${d}</div>`});$('pf-ac-list').innerHTML=h}
function swAc(usn){if(usn===u.usn)return;cMod();chkAuTh();swAuTh('sin');$('sin-usn').value=usn;tst('Re-authentication Required')}
function oMv(src){if(!src)return;vp(15);$('mv-img').src=src;$('media-viewer').classList.add('show')}
function cMv(){$('media-viewer').classList.remove('show');setTimeout(()=>{$('mv-img').src=''},300)}
let dS=1;function oDel(){$('f-del').classList.add('act');dS=1;uDel()}function cDel(){$('f-del').classList.remove('act');$('d-pwd').value=''}
function uDel(){for(let i=1;i<=3;i++){$('ds'+i).classList[dS===i?'add':'remove']('act')}}
function nDel(s){if(s===2)dS=2;if(s===3){let p=$('d-pwd').value;let h=CryptoJS.SHA256(p+u.usn+"KBIOS_SEC").toString();if(h!==u.pwd){tst('Invalid Passphrase',1);vp([50,50]);return}dS=3}if(s===5){let a=JSON.parse(localStorage.getItem('kbs_accounts')||'[]');a=a.filter(x=>x.usn!==u.usn);localStorage.setItem('kbs_accounts',JSON.stringify(a));localStorage.removeItem('kbs_cur_user');cDel();cMod();cDv();chkAuTh();tst('Core Memory Purged')}uDel()}
function oDevPgFromApp(){if(!cApp)return;oDevPg(cApp.dev)}
function oDevPg(n){let f=getDb().filter(x=>x.dev===n);if(!f.length)return;$('dp-nm').innerText=n;$('dp-hdr-nm').innerText=n;let ban=f[0].img&&f[0].img.length?f[0].img[0]:`https://placehold.co/800x400/0f172a/fff?text=${n.replace(/ /g,'+')}`;$('dp-ban').src=ban;$('dp-ic').src=f[0].icon||`https://placehold.co/200/1e293b/fff?text=${n.charAt(0)}`;let td=f.reduce((a,b)=>a+(parseInt((b.downloads||'0').replace(/[^0-9]/g,''))||0),0);$('dp-stats').innerHTML=`<div class="stat-i"><span class="stat-v">${f.length}</span><span class="stat-l">Protocols</span></div><div class="stat-i"><span class="stat-v"><i class="fa-solid fa-download" style="font-size:14px;color:var(--p)"></i> ${td>1000?Math.floor(td/1000)+'K':td}</span><span class="stat-l">Total Installs</span></div>`;$('dp-grd').innerHTML=f.map(x=>cG(x)).join('');$('dev-pg').classList.add('show');$('dp-scrl').scrollTo(0,0);$('dp-hdr-nm').style.opacity=0;history.pushState({p:'devpg'},"")}
function cDevPg(){$('dev-pg').classList.remove('show')}
function shwDl(a){$('dl-ic').src=a.icon||'';$('dl-ti').innerText=a.title;$('dl-sz').innerText=a.size||'10MB';$('dl-perm').style.display='block';$('dl-prog').style.display='none';$('dl-mod').style.display='flex';setTimeout(()=>{$('dl-mod').style.opacity='1';$('dl-bx').style.transform='translateY(0) scale(1)';$('dl-mod').classList.add('act')},50);history.pushState({p:'dl'},"")}
function cDl(){cancelAnimationFrame(dlT);$('dl-mod').style.opacity='0';$('dl-bx').style.transform='translateY(100%) scale(.9)';$('dl-mod').classList.remove('act');setTimeout(()=>$('dl-mod').style.display='none',400)}
function acDl(){if(!navigator.onLine){tst('Network Unavailable',1);vp([50,50]);return}$('dl-perm').style.display='none';$('dl-prog').style.display='block';$('dl-st-txt').innerText='Allocating Storage...';$('dl-pct').innerText='0%';$('dl-bar').style.width='0%';stDl()}
function stDl(){let p=0,lt=performance.now();const up=nt=>{let dt=nt-lt;if(dt>100){p+=Math.random()*4+1;lt=nt;if(p>=100){p=100;$('dl-pct').innerText='100%';$('dl-bar').style.width='100%';$('dl-st-txt').innerText='Decryption Complete';setTimeout(()=>{cDl();let b=$('d-b');b.innerHTML='<i class="fa-solid fa-folder-tree"></i> Open File Manager';b.onclick=()=>{tst('Executing Local Environment...');vp([20,40,20])};b.style.background='var(--t)';tst('Protocol Downloaded Successfully');vp([50,100,50])},600);return}$('dl-pct').innerText=Math.floor(p)+'%';$('dl-bar').style.width=p+'%'}dlT=requestAnimationFrame(up)};dlT=requestAnimationFrame(up)}